### ISSUE TITLE
bug: wrong button link insertion and link and opening the links in a new tab  

### ISSUE THREAD

**Issue by jeonghoyeo7** [Monad-Pad/gmon.link#5]
### Is there an existing issue for this?

- [X] I have looked through the existing issues

### Current Behavior

There are two issues:

1. When a user types links to the button, depending on `http://`, wrong addresses can be inserted. If a user does not type `http://` then `https://gmon.link/` is added.
<Correct addresses>
<img width="451" alt="image" src="https://github.com/user-attachments/assets/06025ad0-21d3-4329-8bbe-443129f40d8b">
<img width="752" alt="image" src="https://github.com/user-attachments/assets/4168c326-88c9-49d9-a8b0-fdf8733c1a50">

<Wrong addresses>
<img width="457" alt="image" src="https://github.com/user-attachments/assets/6564da4c-79e6-4060-8d47-461ddeb6374b">
<img width="744" alt="image" src="https://github.com/user-attachments/assets/bceedc30-3f23-46d0-8d0c-758b6536cbbd">

2. When a user clicks the link of the button, then the site is opened in the same tab, not the new tab.

### Expected Behavior

1. When a user types links to the button, regardless of `http://`, correct addresses should be inserted.
2. When a user clicks the button, the link needs to be opened in the new tab.

### Steps To Reproduce

1. A user can insert the button link in telegram without `http://` e.g., `google.com`, then the button link becomes `https://gmon.link/google.com`

2. A user clicks the button, the site is opened in the same tab.

### Anything else?

Solution

1. This can be handled as exceptions in the telegram bot.

2. This can be fixed by adding `target="_blank"`.

**Comment by elliotdotsol** [comment]
Great issue, your PR was merged successfully
