### ISSUE TITLE
feat: Update TG button title to be more descriptive

### ISSUE THREAD

**Issue by sm2828** [Monad-Pad/gmon.link#7]
### Is there an existing feature request for this?

- [X] I have searched the existing issues and feature requests

### Feature Description

Edit the "Add button(s)" button on TG bot to say "Add/Edit button(s)"

### Problem and Motivation

The 'add button' made me think I was adding another row of buttons. "add/edit button" may be more descriptive.

![Screenshot 2024-09-24 at 9 49 27 AM](https://github.com/user-attachments/assets/d81a76e6-7211-492b-b62a-71389658e4a3)

Motivation: Ease some friction / frustration some user's could face when first using it.

**Comment by elliotdotsol** [comment]
Thanks! I have pushed the update that changes the label, open-source Telegram bot is on the way when I resolve the hosting complexities

**Comment by sm2828** [comment]
Thank you! I'm looking forward to contribute to the tg bot once it is open
